'use strict'

const SOCKET_EVENTS = {
  AUDIO_SYNC: 'audio_sync',
  BOOKMARK_SEEK: 'bookmark_seek',
  CALL_JOINED: 'call_joined',
  CALL_LEFT: 'call_left',
  CONNECT: 'connect',
  CONNECT_ERROR: 'connect_error',
  CONNECTION: 'connection',
  COUPLE_SPACE_UPDATED: 'couple_space_updated',
  CREATE_ROOM: 'create_room',
  DISCONNECT: 'disconnect',
  DOCUMENT_READY: 'document_ready',
  ERROR: 'error',
  FORCE_SYNC_WAIT: 'force_sync_wait',
  FRIEND_ADDED: 'friend_added',
  FRIEND_INVITE: 'friend_invite',
  FRIEND_REQUEST_RECEIVED: 'friend_request_received',
  FRIEND_REQUEST_UPDATED: 'friend_request_updated',
  HOST_TRANSFERRED: 'host_transferred',
  INITIAL_STATE: 'initial_state',
  JOIN_ROOM: 'join_room',
  MEMBER_TIME_UPDATE: 'member_time_update',
  MESSAGE_REACTION_UPDATE: 'message_reaction_update',
  NEW_MESSAGE: 'new_message',
  PEER_JOINED_CALL: 'peer_joined_call',
  PEER_LEFT_CALL: 'peer_left_call',
  REACT_MESSAGE: 'react_message',
  READING_PAGE_UPDATE: 'reading_page_update',
  RELATIONSHIP_TAG_UPDATED: 'relationship_tag_updated',
  REQUEST_PAGE_CHANGE: 'request_page_change',
  REQUEST_PAUSE: 'request_pause',
  REQUEST_PLAY: 'request_play',
  REQUEST_SEEK: 'request_seek',
  RESUME_SYNC_WAIT: 'resume_sync_wait',
  ROOM_EXPIRED: 'room_expired',
  ROOM_JOINED: 'room_joined',
  SEND_MESSAGE: 'send_message',
  SHARED_MEMORY_ADDED: 'shared_memory_added',
  SYNC_PAGE: 'sync_page',
  SYNC_STATE: 'sync_state',
  SYNC_WAITING: 'sync_waiting',
  SYNC_WAITING_RESOLVED: 'sync_waiting_resolved',
  TIME_UPDATE: 'time_update',
  UPLOAD_DOCUMENT: 'upload_document',
  USER_COUNT_UPDATE: 'user_count_update',
  USER_JOINED: 'user_joined',
  USER_LEFT: 'user_left',
  USER_OFFLINE: 'user_offline',
  VIDEO_METADATA: 'video_metadata',
  VIDEO_METADATA_UPDATED: 'video_metadata_updated',
  WEBRTC_ANSWER: 'webrtc_answer',
  WEBRTC_ICE_CANDIDATE: 'webrtc_ice_candidate',
  WEBRTC_OFFER: 'webrtc_offer',
}

module.exports = { SOCKET_EVENTS }
